### ISSUE TITLE
there not work in Linux(Manjaro)

### ISSUE THREAD

**Issue by afunc233** [AvaloniaUtils/AsyncImageLoader.Avalonia#13]
https://github.com/AvaloniaUtils/AsyncImageLoader.Avalonia/blob/93199510cd0c280ea791cecad5d1422f9a7e8931/AsyncImageLoader.Avalonia/Loaders/BaseWebImageLoader.cs#L77

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Scheme()
   at AsyncImageLoader.Loaders.BaseWebImageLoader.LoadFromInternalAsync(String url) in /home/afunc/Projects/AsyncImageLoader.Avalonia/AsyncImageLoader.Avalonia/Loaders/BaseWebImageLoader.cs:line 99

and the params url : /home/afunc/.local/share/PumpkinWindowsConfigurations/CacheImg/1806291fb70687a8b7a13df26fc705df641fed15.png

so maybe we should check the url is localfile first  by use `File.Exists(url)`

**Comment by afunc233** [comment]
or other better way ?
