### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by k-karuna** [AvaloniaUtils/AsyncImageLoader.Avalonia#3]
Hi!
I receive this unhandled exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AsyncImageLoader.Loaders.RamCachedWebImageLoader.ProvideImageAsync(String url)
   at AsyncImageLoader.ImageLoader.OnSourceChanged(Image sender, String url)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Atomex.Client.Desktop.Program.Main(String[] args) in Program.cs:line 11
```

Any suggestions?

**Comment by SKProCH** [comment]
Although on the other hand `ImageLoader.SourceProperty` has a string type, which should not take null according to C# nullable types.  
I need more time to think about the correct behavior of this problem.  

As a temporary fix you can use `TargetNullValue=''` in your binding

**Comment by SKProCH** [comment]
Seems like this is happens due DataContext switching. I make SourceProperty nullable, and it works fine now.

**Comment by k-karuna** [comment]
Great, now it works, thanks!
